server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://nmgxgezubhxfba:c72ab1e61b682bc6f00448b083fe35306efca99a2553cabff99212ce8cc48550@ec2-107-21-10-179.compute-1.amazonaws.com:5432/d4r156b97do1ja
    username: nmgxgezubhxfba
    password: c72ab1e61b682bc6f00448b083fe35306efca99a2553cabff99212ce8cc48550
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Teste backend
  version: 2.0